---
- name: Deploy aplicação Java no EC2
  hosts: app
  become: yes

  vars:
    # Repositório do backend (contém o pom.xml na raiz)
    repo_url: "https://github.com/Matloop/HackatonDevsBack.git"

    # Diretório onde a aplicação será clonada
    app_dir: "/home/ubuntu/app"

    # Nome do .jar final
    jar_name: "app.jar"

  tasks:
    - name: Instala Java e Maven
      apt:
        name:
          - openjdk-17-jdk
          - maven
        state: present
        update_cache: yes

    - name: Clona o repositório do backend
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main

    - name: Gera o .jar do backend
      shell: mvn clean package
      args:
        chdir: "{{ app_dir }}"
      register: build_output

    - name: Copia o .jar final para o diretório base
      copy:
        remote_src: yes
        src: "{{ app_dir }}/target/*.jar"
        dest: "{{ app_dir }}/{{ jar_name }}"
      ignore_errors: yes

    - name: Executa o .jar na porta 8080 com nohup
      shell: "nohup java -jar {{ app_dir }}/{{ jar_name }} > {{ app_dir }}/log.out 2>&1 &"
      args:
        chdir: "{{ app_dir }}"
